### ISSUE TITLE
Adding root variables for all colors found in style.css

### ISSUE THREAD

**Issue by KrystalJean** [KrystalJean/henry-game#1]
Add root to the top of the style.css file right after the import.
Create variables for all of the colors.  The variable names should match the id name, or class name they are found in.

Here is an example:

```
:root {
  --body-color: #fff;
  --guide-box-bg-color: #000;
}
```

```
body {
  color: var(--body-color);
}

#guide-box {
  background-color: var(--guide-box-bg-color);
}
```

**Comment by rithikrajyt** [comment]
Hey @KrystalJean , I want to solve this issue under Hacktoberfest.
Can you please assign this issue to me??

**Comment by KrystalJean** [comment]
HI @rithikrajyt . I will go ahead, and assign you for all of these issues as you requested.  Just make sure to work on one thing at a time to keep your pull request organized within the proper issue.  Let me know if you have any questions.

**Comment by rithikrajyt** [comment]
Sure @KrystalJean,I will work on issues one by one as given priorities by you and will keep you posted on the development. Thanks for assigning me

**Comment by KrystalJean** [comment]
Awesome @rithikrajyt . Thank you for your help.  I will be signing off soon for the evening, but will check back frequently.
It will be best if you can work on this issue first, and the others can be done in any order.
