### ISSUE TITLE
Improve the Start Button style

### ISSUE THREAD

**Issue by KrystalJean** [KrystalJean/henry-game#3]
Improve the Start Button style to look more like the real thing.  Check out the images in the README.md . 
Notice how the Start button has the horizontal line that turns down on the ends, and the six raised dots below that.

**Comment by rithikrajyt** [comment]
Hey @KrystalJean , I want to solve this issue under Hacktoberfest.
Can you please assign this issue to me??

**Comment by Anuragmourya975** [comment]
I would like to solve this issue under Hacktoberfest. Can you please assign this issue to me?

**Comment by KrystalJean** [comment]
@Anuragmourya975 This issue is already assigned.

**Comment by jqaustin** [comment]
can I work on this for hacktoberfest
