### ISSUE TITLE
Improve the Henry button style

### ISSUE THREAD

**Issue by KrystalJean** [KrystalJean/henry-game#5]
Improve the Henry button to look more like the real thing.  Please check README.md for details.

**Comment by rithikrajyt** [comment]
Hey @KrystalJean , I want to solve this issue under Hacktoberfest.
Can you please assign this issue to me??

**Comment by Anuragmourya975** [comment]
I would like to solve this issue under Hacktoberfest. Can you please assign this issue to me?

**Comment by KrystalJean** [comment]
@Anuragmourya975 This issue is already assigned.

**Comment by jqaustin** [comment]
I would like to work on this for Hacktoberfest.

**Comment by KrystalJean** [comment]
ok @jqaustin

**Comment by KrystalJean** [comment]
Thank you @jqaustin .
