### ISSUE TITLE
Create an "LED" light

### ISSUE THREAD

**Issue by KrystalJean** [KrystalJean/henry-game#6]
Create an LED light directly below the Henry button that looks as realistic as possible to the real game.  Please check the README.md file for more info.  

  You will just be completing the design, and should not worry about functionality.  
You should have the led light up on hover for now.  At a later time I will change the LED to light up during certain game play events, rather than on hover, but it will keep the style that you create.

**Comment by rithikrajyt** [comment]
Hey @KrystalJean , I want to solve this issue under Hacktoberfest.
Can you please assign this issue to me??

**Comment by Anuragmourya975** [comment]
I would like to solve this issue under Hacktoberfest. Can you please assign this issue to me?
