### ISSUE TITLE
Add manufacturer logo

### ISSUE THREAD

**Issue by KrystalJean** [KrystalJean/henry-game#7]
Add the Tiger ("Tiger Electronics") logo next to the LED button, underneath the Henry Button.  The LED button is A PENDING ISSUE #6  so be aware that you may not see it yet.
If so, you may center it under the Henry button for now.

**Comment by rithikrajyt** [comment]
Hey Krystal, I want to solve this issue under Hacktoberfest.
Can you please assign this issue to me??

**Comment by KrystalJean** [comment]
Yes, @rithikrajyt you got it. Let me know if you have any questions.

**Comment by Anuragmourya975** [comment]
I would like to solve this issue under Hacktoberfest. Can you please assign this issue to me?
